order_statuses = {
    "ORD123": {
        "status": "Shipped",
        "name": "Product A",
        "qty": 2,
        "price": 100,
        "description": "This is a description of Product A",
    },
    "ORD456": {
        "status": "Delivered",
        "name": "Product B",
        "qty": 1,
        "price": 50,
        "description": "This is a description of Product B",
    },
    "ORD789": {
        "status": "Pending",
        "name": "Product C",
        "qty": 3,
        "price": 150,
        "description": "This is a description of Product C",
    },
    "ORD101": {
        "status": "In Transit",
        "name": "Product D",
        "qty": 4,
        "price": 200,
        "description": "This is a description of Product D",
    },
    "ORD112": {
        "status": "Out for Delivery",
        "name": "Product E",
        "qty": 5,
        "price": 250,
        "description": "This is a description of Product E",
    },
    "ORD131": {
        "status": "Processing",
        "name": "Product F",
        "qty": 6,
        "price": 300,
        "description": "This is a description of Product F",
    },
    "ORD141": {
        "status": "On Hold",
        "name": "Product G",
        "qty": 7,
        "price": 350,
        "description": "This is a description of Product G",
    },
    "ORD151": {
        "status": "Cancelled",
        "name": "Product H",
        "qty": 8,
        "price": 400,
        "description": "This is a description of Product H",
    },
    "ORD161": {
        "status": "Returned",
        "name": "Product I",
        "qty": 9,
        "price": 450,
        "description": "This is a description of Product I",
    },
    "ORD171": {
        "status": "Refunded",
        "name": "Product J",
        "qty": 10,
        "price": 500,
        "description": "This is a description of Product J",
    },
}
